version: "3.4"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - "mydata_grafana:/var/lib/grafana"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: test
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10.1-alpine
    volumes:
      - "mydata_postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: test
volumes:
  mydata_postgres:
  mydata_grafana:

