version: "3"
services:
  spark-master:
    image: dmitryit/spark-base:latest
    command: master
    volumes:
      - "/Users/dmitry/Docker/spark_and_python/data:/data"
    networks:
      - spark_network
    ports:
      - "8080:8080"
      - "8888:8888"

  spark-slave:
    image: dmitryit/spark-base:latest
    command: slave "spark://spark-master:7077"
    volumes:
      - "/Users/dmitry/Docker/spark_and_python/data:/data"
    networks:
      - spark_network
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    deploy:
      replicas: 3


networks:
  spark_network:

volumes:
  spark_data:
