version: "3"
services:
  spark-master:
    image: dmitryit/spark-base:latest
    command: master
    networks:
      - spark_network
    ports:
      - "8080:8080"
      - "8888:8888"

  spark-slave:
    image: dmitryit/spark-base:latest
    command: slave "spark://spark-master:7077"
    networks:
      - spark_network
    depends_on:
      - spark-master
    deploy:
      replicas: 3


networks:
  spark_network:
