FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y curl vim git wget && \
    mkdir spacevim && \
    cd spacevim && \
    curl -sLf https://spacevim.org/install.sh | bash     
ENTRYPOINT ["bash"]
